### ISSUE TITLE
Simple 1D interpolation is not working

### ISSUE THREAD

**Issue by Dale-Black** [PumasAI/DataInterpolations.jl#127]
```julia
using DataInterpolations

kVs = [80, 100, 120] # independent variable
HUs = [177, 145, 130] # dependent variable

itp = QuadraticInterpolation(kVs, HUs)

itp(kVs[1]) == HUs[1]
```

The code above returns `false` when it should return `true`. Not sure what is wrong, but also attached a screenshot after plotting this example

![image](https://user-images.githubusercontent.com/62632960/197263879-87d3fa32-7afb-44e2-bfa8-26cb0b6657dc.png)

**Comment by DaniGlez** [comment]
The constructor has its arguments reversed in your example, it's `QuadraticInterpolation(u,t)` (ie first the dependent variable and then the independent variable). Use `itp = QuadraticInterpolation(HUs, kVs)` instead and it'll work just as you expect. I can see how it's confusing if you're used to the `interp1d(x,y)` syntax in other languages.

**Comment by Dale-Black** [comment]
Oh thanks!
