### ISSUE TITLE
Test LOESS

### ISSUE THREAD

**Issue by andreasnoack** [PumasAI/DataInterpolations.jl#56]
The coverage report reveals the LOESS based interpolation doesn't have test coverage. Ref  #36

**Comment by sipah00** [comment]
@andreasnoack @ChrisRackauckas I think it would be better to write wrapper on https://github.com/JuliaStats/Loess.jl so that it fits to DataInterpolations.jl API, instead of having our own implementation?

**Comment by ChrisRackauckas** [comment]
Yes, just making it a wrapper is probably a better idea.

**Comment by fab4ap** [comment]
I found that Loess has been removed. Hope it will be reintroduced. My code now breaks. The Loess.jl package did not work so I used DataInterpolations.Loess

**Comment by andreasnoack** [comment]
It might get reintroduced at some point but will then most likely be based on Loess.jl. You should probably try to figure out why it doesn’t work for you.

I’ll close this issue since Loess support has been removed.

**Comment by niclasmattsson** [comment]
Then you might want to consider removing the Loess example from the tutorial too.

**Comment by fab4ap** [comment]
Hope the original version will get reintroduced - because Loess.jl never
worked for me in spite of repeated attempts. The original one worked great
but since it was taken out, my work is unfortunately broken now. Well, back
to R for all such work - as long as RCall continues to work!
