### ISSUE TITLE
Allow interpolating `AbstractVector{<:AbstractVector}`

### ISSUE THREAD

**Issue by goretkin** [PumasAI/DataInterpolations.jl#67]
if `function (A::LinearInterpolation{<:AbstractVector{<:Number}})(t::Number)` were generalized beyond `<:Number` to perhaps `<:AbstractVector` then

1. You could support e.g. `Vector{SVector}`
2. `function (A::LinearInterpolation{<:AbstractMatrix{<:Number}})(t::Number)` could be written in terms of a `reinterpret`/`reshape` and the previous definition. The package would have to come to depend on [StaticArrays.jl](https://github.com/JuliaArrays/StaticArrays.jl), as far as I can tell, however.

And so on for the interpolation methods that only require vector space operations on the data.

**Comment by baggepinnen** [comment]
It would be great to have some way of interpolating vector-valued time series, e.g., 
```julia
CubicInterpolation(t, u, dims=1)
```
if `u` is a matrix with time in the first dimension.

**Comment by baggepinnen** [comment]
The `Vector{SVector}` case works after #78.

**Comment by andreasnoack** [comment]
Fixed by #78
